### ISSUE TITLE
EXPERIENCE RAILS

### ISSUE THREAD

**Issue by bachpx195** [bachpx195/experience#20]
Everything about Ruby on Rails

root_path -> '/'
root_url  -> 'http://www.example.com/'

help_path -> '/help'
help_url  -> 'http://www.example.com/help'

```
Note that we’ve written

redirect_to @user
where we could have used the equivalent

redirect_to user_url(@user)

```

```
edit_account_activation_url(@user.activation_token, ...)
Recalling that

edit_user_url(user)
produces a URL of the form

http://www.example.com/users/1/edit
the corresponding account activation link’s base URL will look like this:

http://www.example.com/account_activations/q5lt38hQDc_959PVoo6b7A/edit

edit_account_activation_url(@user.activation_token, email: @user.email)
account_activations/q5lt38hQDc_959PVoo6b7A/edit?email=foo%40example.com
```

**Comment by bachpx195** [comment]
Rails command line
### **-  generate controller + view:** 
`rails g controller 'controllername' 'new' 'create'`

### **-  generate controller + view with all restful function:** 
`rails g scaffold_controller 'Message'`

### **- generate scaffold and migrate db**
```
rails generate scaffold LineItem product:references cart:belongs_to
...
rails db:migrate
```
### **- [under scaffold](http://stackoverflow.com/questions/963420/undo-scaffolding-in-rails)**
```
rake db:rollback
rails destroy scaffold MyFoo
```
### **- generate column to table**
`rails generate migration add_quantity_to_line_items quantity:integer`
`db:migrate
`

**Comment by bachpx195** [comment]
# **Rails function helper**

-  ## convert html from DB to text view
><%= sanitize(product.description) %>
- ## **format number** 
> <%= sprintf("$%0.02f", product.price) %>
> built-in: number_to_currency() 

- ## **[build() method activeRecord](http://stackoverflow.com/questions/19761766/build-method-on-ruby-on-rails)**
giống với object.new(parmas) nhưng ko lưu trực tiếp vào db mà vào bộ nhớ để có thể gọi ra view.

> You misunderstood build. It's just an alias of new, nothing special. https://github.com/rails/rails/blob/959fb8ea651fa6638aaa7caced20d921ca2ea5c1/activerecord/lib/active_record/relation.rb#L84
> 
> build won't "create" a record in database, just create a new object in memory so that the view can take this object and display something, especially for a form.

 @line_item = @cart.line_items.build(product: product)

- ## **find_by()**
The find_by() method is a streamlined version of the where() method. Instead of returning an array of results, it returns either an existing LineItem or nil.

- ## **[content_tag()](http://apidock.com/rails/ActionView/Helpers/TagHelper/content_tag)**
Tạo ra 1 thẻ htmt với nội dung bên trong
content_tag(name, content_or_options_with_block = nil, options = nil, escape = true, &block) public
```
content_tag(:p, "Hello world!")
 # => <p>Hello world!</p>
content_tag(:div, content_tag(:p, "Hello world!"), class: "strong")
 # => <div class="strong"><p>Hello world!</p></div>
content_tag(:div, "Hello world!", class: ["strong", "highlight"])
 # => <div class="strong highlight">Hello world!</div>
content_tag("select", options, multiple: true)
 # => <select multiple="multiple">...options...</select>

<%= content_tag :div, class: "strong" do -%>
  Hello world!
<% end -%>
 # => <div class="strong">Hello world!</div>
```
- ## **provide()**
cung cap 1 bien dung chung cho ca application va view
<% provide :title, "About" %>

- ## **.Object**
`form_for(@user) do |f|
`f.object is @user, and in

`form_for(@micropost) do |f|
`f.object is @micropost, etc.

**Comment by bachpx195** [comment]
## **Sự thông minh của Rails?**

- Thêm id của sản phẩm được khai báo ngầm trong hàm create() (POST)
` line_items_path(product_id: product) % `

**Comment by bachpx195** [comment]
# **ACTIVE RECORD**
object.function => object of function
find_id: lấy 1 phần tử đầu tiên
where: lấy một mảng các đối tượng
where ko dc dùng để tìm các association
```
Admin::Bill.where(agreement_id: 46).agreement
  Admin::Bill Load (10.1ms)  SELECT `bills`.* FROM `bills` WHERE `bills`.`agreement_id` = 46
NoMethodError: undefined method `agreement' for #<Admin::Bill::ActiveRecord_Relation:0x7a78118>
from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/relation/delegation.rb:123:in `method_missing'
```

**Comment by bachpx195** [comment]
# **Model**
Functions trong model đều trả về giá trị **object.method()**
```
  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item
  end
```
VD trên, model trả về dạng **Cart.current_item** ~ **Cart.line_items.find_by(product_id: product.id)**

## **assocation model**
author.book = book.where(author: author)

## **[Strong parmas (permit)](https://viblo.asia/Chym/posts/ZnbRlDNQR2Xo)**

- StrongParameters là 1 phương pháp để đối phó với lỗi bảo mật khi sử dụng tính năng Mass Assignment.

- Mass Assignment là 1 tính năng cực kì tiện lợi cho phép update 1 model – khi tạo mới hoặc thay đổi – bằng hash của Ruby.

```
 def update
    user = current_user
    # params = {name: "Rock Khuya", email: "sample@gmail.com"}
    user.update(user_params)
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
```
Update hàng loạt, yêu cầu các parmas có :user, :email 

## **[Model-name].errors**
```
irb(main):009:0> user.update_attributes(remember_token: 1).errors
   (0.4ms)  BEGIN
  User Exists (0.3ms)  SELECT  1 AS one FROM `users` WHERE `users`.`email` = 'example@railstutorial.org' AND (`users`.`id` != 1) LIMIT 1
   (0.1ms)  ROLLBACK

irb(main):010:0> user.errors
=> #<ActiveModel::Errors:0x00000003087a70 @base=#<User id: 1, name: "skyy", email: "example@railstutorial.org", created_at: "2017-02-15 07:49:10", updated_at: "2017-02-15 07:49:10", password_digest: "$2a$10$UJwa.Aqdsvv30ZcRGKFuzenhwfar2NmrDSoSdH8aV31...", birthday: nil, remember_digest: nil>, @messages={:password=>["can't be blank"]}, @details={:password=>[{:error=>:blank}]}>
```

**Comment by bachpx195** [comment]
# **AJAX**
rails50/depot_l/app/views/line_items/create.js.erb
$('#cart').html("<%=j render(@cart) %>");
This simple template tells the browser to replace the content of the element
whose id is cart with that HTML.
Let’s analyze how it manages to do that.
For simplicity and conciseness, the jQuery library is aliased to $, and most
usages of jQuery start there.
The first call—$('#cart')—tells jQuery to find the HTML element that has an id of
cart. The html() method1
 is then called with a first argument of the desired
replacement for the contents of this element. This content is formed by a call
to the render() method on the @cart object. The output of this method is processed
1. http://api.jquery.com/html/
report erratum • discuss
Iteration F2: Creating an Ajax-Based Cart • 155
by an escape_javascript() helper method, using a convenient alias named j(), that
converts this Ruby string into a format acceptable as input to JavaScript.
Note that this script is executed in the browser. The only parts executed on
the server are the portions within the <%= and %> delimiters.
Does it work? Well, it’s hard to show in a book, but it sure does. Make sure
you reload the index page to get the remote version of the form and the
JavaScript libraries loaded into your browser. Then, click one of the Add to
Cart buttons. You should see the cart in the sidebar update. And you shouldn’t
see your browser show any indication of reloading the page. You’ve just created
an Ajax application.

**Comment by Ingosmar89219** [comment]
im noob in rails somone can help me? i got this error 
NoMethodError in Comments#create

Showing /home/noeblack/Descargas/empresa-proyecto/app/views/comments/new.html.haml where line #6 raised:

undefined method `each' for nil:NilClass

My view new.html.haml
.col-lg-10.col-lg-offset-1.top-space
 .panel.panel-default
  .panel-heading
   %h2 Comentarios de clientes
  .panel-body
   - @comments.each do |comment|
    .media     
     =image_tag comment.img_user, class: "media-object pull-left img-circle tam_comments"
    .media-body
     %h4= comment.name
      
     %small.move_date= comment.created_at
       
     %p.move_comment= comment.comment  
   %hr.max-width
-if user_signed_in?
 .col-lg-10.col-lg-offset-1
  .card.large-padding
   = form_for @comment,builder: BootstrapFormBuilder do |f|
    = f.text_area :comment
    = f.submit "Publicar"

My controller 
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:new]

  # GET /comments
  # GET /comments.json
  def index
    if user_signed_in? && current_user.id == 1 && current_user.kind_user == 'Administrador' && current_user.role_id == 1
      @comments = Comment.all
    else
      redirect_to root_path
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    if user_signed_in? && current_user.id == 1 && current_user.kind_user == 'Administrador' && current_user.role_id == 1
      @comments = Comment.find(params[:id])
    else
      redirect_to root_path
    end        
  end

  # GET /comments/new
  def new
    @comments = Comment.select("img_user, name, created_at, comment").where("validate_comment" => "true")

    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
    if user_signed_in? && current_user.id == 1 && current_user.kind_user == 'Administrador' && current_user.role_id == 1
      redirect_to edit_comment_path
    else
      redirect_to root_path
    end
  end

  # POST /comments
  # POST /comments.json
  def create    
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.name = current_user.name
    @comment.img_user = current_user.img_user   
    
    respond_to do |format|
      if @comment.save
        format.html { redirect_to new_comment_path, notice: 'Comment was successfully created.' }
        format.json { render :new, status: :created, location: @comment }

      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end

  end
  

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    if user_signed_in? && current_user.id == 1 && current_user.kind_user == 'Administrador' && current_user.role_id == 1
      respond_to do |format|
        if @comment.update(comment_params)
          format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
          format.json { render :show, status: :ok, location: @comment }
        else
          format.html { render :edit }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    if user_signed_in? && current_user.id == 1 && current_user.kind_user == 'Administrador' && current_user.role_id == 1
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to root_path
    end
  end
  
  
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :name, :comment, :img_user, :validate_comment)
    end

    
end
PLEASE HELP ME! thanks guys

**Comment by bachpx195** [comment]
@# **[Websocket](https://blog.heroku.com/real_time_rails_implementing_websockets_in_rails_5_with_action_cable)**
http://www.thegreatcodeadventure.com/rails-5-action-cable-with-multiple-chatroom-subscriptions/

**Comment by bachpx195** [comment]
How to find all files with the same extension within a directory:
find . -type f -name "*.txt"
