### ISSUE TITLE
PHP storm

### ISSUE THREAD

**Issue by bachpx195** [bachpx195/experience#6]
Các phím tắt:
Ctrl+ space: auto complete.
Alt + f7: search
Ctrl+ q: js
Ctrl + b: chuyển đến định nghĩa hàm hoặc biến
Ctrl + f6: đổi tên cho biến
Ctrl + P: gợi ý hàm cho biến
Ctrl+Shift+f7: tìm kiếm và thay thế.
Ctrl+E: list ra các file đã dùng
Ctrl+Shift+N: tim file.
Ctrl+shift+z: redo

**Comment by bachpx195** [comment]
Trick:
Format code: code -> reformat (Ctrl+ alt + L)

**Comment by bachpx195** [comment]
install and configure
https://confluence.jetbrains.com/display/PhpStorm/Installing+and+Configuring+XAMPP+with+PhpStorm+IDE

**Comment by dongta195** [comment]
install and configure
https://confluence.jetbrains.com/display/PhpStorm/Installing+and+Configuring+XAMPP+with+PhpStorm+IDE

**Comment by bachpx195** [comment]
Cài đặt project laravel php storm
https://github.com/barryvdh/laravel-ide-helper

**Comment by dongta195** [comment]
cài php storm full crack
http://vutienit.com/download-phpstorm-2016-full-crack-active-phan-men-code-php-tot-nhat/

**Comment by bachpx195** [comment]
https://github.com/bodiam/intellij-bootstrap3
